import { Agent, Skill } from '@/types';

export const APP_NAME = '涓€冩彁鍒?AI 绉佹暀';
export const APP_DESC = '6 浣?AI 涓撳 路 55 涓牳蹇冩妧鑳?路 涓撳睘涓€冪鏁?;

export const AGENTS: Agent[] = [
  {
    id: 'math-tutor',
    name: '绠楁棤閬?,
    title: '鏁板鍘嬭酱鏁欑粌',
    description: '涓撴敾涓€冩暟瀛﹀帇杞撮锛?4涓妧鑳借鐩栦簩娆″嚱鏁般€佸嚑浣曟瀯閫犮€佸垎绫昏璁虹瓑绫诲瀷',
    avatar: '馃搻',
    color: '#3B82F6',
    skills: [
      { id:'math01', name:'浜屾鍑芥暟鏈€鍊间笌鑼冨洿鍒嗘瀽', description:'瀹氳酱瀹氬尯闂?瀹氳酱鍔ㄥ尯闂?鍔ㄨ酱瀹氬尯闂翠笁绉嶅満鏅?, subject:'math', steps:['閰嶆柟鍖栭《鐐瑰紡','鍒ゆ柇鍦烘櫙绫诲瀷','鎸夊満鏅墽琛?,'楠岃瘉鍚堢悊鎬?], triggers:['鏈€澶у€兼槸椤剁偣鍚?,'浠€涔堟椂鍊欑湅绔偣','瀵圭О杞翠綅缃?], boundaries:['鏃犲尯闂撮檺鍒朵笉鐢?,'涓€娆″嚱鏁颁笉鐢?], examples:['2024T22绁ㄤ环','2023鑿卞舰闈㈢Н'], tags:['浜屾鍑芥暟','鏈€鍊?] },
      { id:'math02', name:'鍘嬭酱棰樼患鍚堢牬瑙ｆ€濊矾', description:'璇婚-瀹氫綅-鐮村眬涓夋娉曟媶瑙ｅ帇杞撮', subject:'math', steps:['璇婚鍒掑叧閿?,'瀹氫綅鐭ヨ瘑鐐?,'閫夊垏鍏ョ偣','鍒嗘鎺ㄨ繘','楠岃瘉'], triggers:['瀹屽叏娌℃€濊矾','涓嶇煡閬撲粠鍝笅鎵?], boundaries:['绠€鍗曢涓嶉渶瑕?], examples:['2024鍘嬭酱棰?], tags:['鍘嬭酱棰?,'绛栫暐'] },
      { id:'math03', name:'鍒嗙被璁ㄨ鎬濇兂', description:'鍙傛暟璁ㄨ銆佸浘褰綅缃璁虹殑绯荤粺鏂规硶璁?, subject:'math', steps:['纭畾鍒嗙被鏍囧噯','绌蜂妇鎵€鏈夋儏鍐?,'鍒嗗埆姹傝В','鍚堝苟缁撴灉'], triggers:['闇€瑕佸垎绫昏璁哄悧','鍒嗗嚑绉嶆儏鍐?], boundaries:['涓嶅彲閬楁紡鎯呭喌'], examples:['鍔ㄧ偣闂'], tags:['鍒嗙被璁ㄨ'] },
      { id:'math04', name:'瀛樺湪鎬ч棶棰樺垎绫昏璁?, description:'鍒ゆ柇鏄惁瀛樺湪鐐?绾挎婊¤冻鏉′欢', subject:'math', steps:['鍋囪瀛樺湪','寤虹珛鏂圭▼','姹傝В楠岃瘉','涓嬬粨璁?], triggers:['鏄惁瀛樺湪杩欐牱鐨勭偣','鏄惁鍙兘'], boundaries:['楠岃瘉瑙ｅ湪鑼冨洿鍐?], examples:['瀛樺湪鐐筆'], tags:['瀛樺湪鎬?] },
      { id:'math05', name:'鏂板畾涔夎繍绠椾笌瑙勫垯', description:'鑷畾涔夎繍绠楃鍙峰拰瑙勫垯鐨勭悊瑙ｅ簲鐢?, subject:'math', steps:['鐞嗚В鏂板畾涔?,'杞寲涓哄父瑙勮繍绠?,'鎵ц璁＄畻','楠岃瘉'], triggers:['瀹氫箟鏂拌繍绠?,'瑙勫畾'], boundaries:['涓ユ牸閬靛畧瀹氫箟'], examples:['鏂板畾涔夐'], tags:['鏂板畾涔?] },
      { id:'math06', name:'涓夋寮忔帹鐞?, description:'鍥犱负鈫掓墍浠モ啋鍥犳鐨勬暟瀛﹁瘉鏄庢鏋?, subject:'math', steps:['鏄庣‘宸茬煡','閫愬眰鎺ㄥ','寰楃粨璁?], triggers:['璇佹槑棰?,'姹傝瘉'], boundaries:['姣忎竴姝ヨ鏈変緷鎹?], examples:['鍑犱綍璇佹槑'], tags:['鎺ㄧ悊'] },
      { id:'math07', name:'鏃嬭浆鏋勯€犲叏绛夋ā鍨?, description:'鏃嬭浆鍙樻崲鏋勯€犲叏绛変笁瑙掑舰', subject:'math', steps:['璇嗗埆鏃嬭浆涓績','纭畾鏃嬭浆瑙掑害','鏋勯€犲叏绛?,'鍒╃敤鎬ц川姹傝В'], triggers:['鏃嬭浆','杞姩','缁曠偣'], boundaries:['娉ㄦ剰鏃嬭浆鏂瑰悜'], examples:['鏃嬭浆鏋勯€?], tags:['鏃嬭浆','鍏ㄧ瓑'] },
      { id:'math08', name:'杈呭姪绾挎坊鍔犳妧宸?, description:'鍊嶉暱涓嚎銆佹埅闀胯ˉ鐭€佷綔骞宠绛?, subject:'math', steps:['瑙傚療鍥惧舰鐗瑰緛','閫夎緟鍔╃嚎绫诲瀷','娣诲姞杈呭姪绾?,'鍒╃敤鏂板浘褰㈡眰瑙?], triggers:['瑕佸仛杈呭姪绾垮悧','鎬庝箞鍔?], boundaries:['杈呭姪绾夸笉鏄秺澶氳秺濂?], examples:['鍊嶉暱涓嚎'], tags:['杈呭姪绾?] },
      { id:'math09', name:'鍦嗘ā鍨嬬患鍚?, description:'鍨傚緞瀹氱悊銆佸渾鍛ㄨ瀹氱悊銆佸垏绾挎€ц川绛?, subject:'math', steps:['璇嗗埆鍦嗗厓绱?,'鎻愬彇鍦嗙殑鎬ц川','缁撳悎鍏朵粬鍥惧舰姹傝В'], triggers:['鍦?,'鍦嗗懆瑙?,'鍒囩嚎'], boundaries:['娉ㄦ剰鐩村緞瀵圭洿瑙?], examples:['鍦嗕笌涓夎褰?], tags:['鍦?] },
      { id:'math10', name:'鐩镐技妯″瀷缁煎悎', description:'A瀛楀瀷銆?瀛楀瀷銆並瀛楀瀷鐩镐技妯″瀷', subject:'math', steps:['鎵惧搴旇','纭畾鐩镐技姣?,'鍒楁瘮渚嬪紡','姹傝В'], triggers:['鐩镐技','瀵瑰簲鎴愭瘮渚?], boundaries:['瀵瑰簲杈硅瀵瑰簲濂?], examples:['A瀛楀瀷鐩镐技'], tags:['鐩镐技'] },
      { id:'math11', name:'鏈€鐭矾寰勪笌鏈€鍊奸棶棰?, description:'灏嗗啗楗┈銆佽儭涓嶅綊銆侀樋姘忓渾绛夋渶鍊兼ā鍨?, subject:'math', steps:['璇嗗埆鏈€鍊兼ā鍨?,'浣滃绉扮偣','杩炴帴姹傝В'], triggers:['鏈€鐭?,'鏈€灏?,'鏈€澶ц窛绂?], boundaries:['涓嶅悓妯″瀷鐢ㄤ笉鍚屾柟娉?], examples:['灏嗗啗楗┈'], tags:['鏈€鍊?,'璺緞'] },
      { id:'math12', name:'涓€棰樺瑙ｄ笌瑙ｆ硶瀵规瘮', description:'浠庝唬鏁般€佸嚑浣曘€佸嚱鏁板瑙掑害姹傝В', subject:'math', steps:['鎵句唬鏁扮壒寰?,'鎵惧嚑浣曠壒寰?,'閫夋渶浼樿В娉?], triggers:['鏈夊叾浠栬В娉曞悧','鍝鏇村ソ'], boundaries:['姣旇緝浼樺姡'], examples:['浠ｆ暟鍑犱綍鍙岃В'], tags:['澶氳В'] },
      { id:'math13', name:'鐗规畩鍒颁竴鑸綊绾虫硶', description:'浠庣壒娈婃儏褰㈡壘瑙勫緥锛屾帹骞垮埌涓€鑸粨璁?, subject:'math', steps:['鍙栫壒娈婂€?,'瑙傚療瑙勫緥','鎺ㄥ箍鍒颁竴鑸?,'璇佹槑'], triggers:['鎵捐寰?,'鐚滄兂'], boundaries:['闇€璇佹槑涓€鑸粨璁?], examples:['鏁板垪瑙勫緥'], tags:['褰掔撼'] },
      { id:'math14', name:'涓偣涓庤骞冲垎绾挎ā鍨?, description:'涓偣鍜岃骞冲垎绾跨殑鎬ц川涓庡簲鐢?, subject:'math', steps:['璇嗗埆涓偣鎴栬骞冲垎绾?,'搴旂敤鎬ц川','缁撳悎鏉′欢姹傝В'], triggers:['涓偣','瑙掑钩鍒嗙嚎'], boundaries:['娉ㄦ剰涓綅绾挎潯浠?], examples:['涓偣鍥涜竟褰?], tags:['涓偣','瑙掑钩鍒嗙嚎'] },
    ],
  },
  {
    id: 'physics-tutor',
    name: '鍔涙嫈灞?,
    title: '鐗╃悊瀹為獙鏁欑粌',
    description: '涓撴敾鐗╃悊鍘嬭酱棰樹笌瀹為獙鎺㈢┒锛?0涓妧鑳借鐩栧姏瀛︺€佺數瀛︺€佸厜瀛﹀叏閮ㄩ噸鐐?,
    avatar: '鈿?,
    color: '#10B981',
    skills: [
      { id:'phy01', name:'鍘嬪己娴姏缁煎悎妯″瀷', description:'鍥轰綋娑蹭綋鍘嬪己涓庢诞鍔涚殑缁煎悎璁＄畻', subject:'physics', steps:['鐘舵€佸垽瀹?,'鍙楀姏鍒嗘瀽','鍏紡灞曞紑','杩為攣鎺ㄥ','楠岃瘉'], triggers:['鍘嬪己鍜屾诞鍔?,'娌夊簳婕傛诞'], boundaries:['绾數瀛︿笉鐢?], examples:['2024鍘嬭酱棰?], tags:['鍘嬪己','娴姏'] },
      { id:'phy02', name:'鍔ㄦ€佺數璺瀬鍊煎垎鏋?, description:'婊戝彉绉诲姩寮曡捣鐨勭數娴佺數鍘嬪姛鐜囧彉鍖?, subject:'physics', steps:['鍒嗘瀽鐢佃矾缁撴瀯','纭畾婊戝彉鑼冨洿','璁＄畻鏋佸€?], triggers:['婊戠墖绉诲姩','鏈€澶у姛鐜?], boundaries:['纭涓茶仈骞惰仈'], examples:['婊戝彉鏈€鍊?], tags:['鐢佃矾','鏋佸€?] },
      { id:'phy03', name:'鏉犳潌婊戣疆缁勭患鍚?, description:'鏉犳潌骞宠　鍜屾粦杞粍鍙楀姏鐨勭患鍚堣绠?, subject:'physics', steps:['纭畾鏀偣','鍒嗘瀽鍔涜噦','鍒楀钩琛℃柟绋?,'姹傝В'], triggers:['鏉犳潌','婊戣疆'], boundaries:['娉ㄦ剰缁冲瓙娈垫暟'], examples:['鏉犳潌婊戣疆缁勫悎'], tags:['鏉犳潌','婊戣疆'] },
      { id:'phy04', name:'鑳芥簮璁＄畻涓撻', description:'鍔熴€佸姛鐜囥€佹満姊版晥鐜囥€佽兘閲忚浆鍖栬绠?, subject:'physics', steps:['纭畾鑳介噺褰㈠紡','鍒楄兘閲忓叕寮?,'浠ｅ叆鏁版嵁'], triggers:['鏁堢巼','鍔熺巼','鍋氬姛'], boundaries:['娉ㄦ剰鍗曚綅鎹㈢畻'], examples:['鏈烘鏁堢巼'], tags:['鑳芥簮','鏁堢巼'] },
      { id:'phy05', name:'鐢靛缁煎悎璁＄畻', description:'娆у瀹氬緥銆佺數鍔熺巼銆佺劍鑰冲畾寰嬬患鍚堝簲鐢?, subject:'physics', steps:['鐢荤瓑鏁堢數璺?,'鏍囧凡鐭ラ噺','閫夊叕寮忔眰瑙?], triggers:['鐢靛姛鐜?,'娆у瀹氬緥'], boundaries:['鍖哄垎绾數闃?], examples:['澶氭尅浣嶇敤鐢靛櫒'], tags:['鐢靛','鍔熺巼'] },
      { id:'phy06', name:'娴姏澶氱姸鎬佽绠?, description:'鍚屼竴鐗╀綋鍦ㄤ笉鍚岀姸鎬佷笅鐨勬诞鍔涘垎鏋?, subject:'physics', steps:['鍒嗘瀽鍚勭姸鎬?,'鍒楀钩琛℃柟绋嬬粍','鑱旂珛姹傝В'], triggers:['婕傛诞鎮诞','娌夊簳'], boundaries:['涓嶅悓鐘舵€佸垎鍒垎鏋?], examples:['涓€鐗╁鐘舵€?], tags:['娴姏','澶氱姸鎬?] },
      { id:'phy07', name:'鐗╃悊浼版祴涓庡父璇?, description:'甯歌鐗╃悊閲忕殑浼版祴鍊?, subject:'physics', steps:['鍥炲繂甯歌鍊?,'瀵规瘮閫夐」','鎺掗櫎涓嶅悎鐞?], triggers:['浼版祴','鏈€鎺ヨ繎'], boundaries:['璁颁綇鏍囧噯鍊?], examples:['鏁欏楂樺害'], tags:['浼版祴'] },
      { id:'phy08', name:'鐗╃悊澶氶€夐鐮磋В', description:'澶氶€夊棰樺拰鎺掗櫎娉曟妧宸?, subject:'physics', steps:['瀹￠骞查櫡闃?,'閫愪釜閫夐」鍒嗘瀽','鎺掗櫎鏄庢樉閿?], triggers:['澶氶€夐','浠ヤ笅姝ｇ‘鐨?], boundaries:['瀹佸皯閫変笉閿欓€?], examples:['澹扮幇璞″閫?], tags:['澶氶€?] },
      { id:'phy09', name:'鐗╃悊瀹為獙鎺㈢┒', description:'鎺у埗鍙橀噺娉曘€佽浆鎹㈡硶绛夊疄楠屾柟娉?, subject:'physics', steps:['鏄庣‘瀹為獙鐩殑','閫夊疄楠屾柟娉?,'璁捐姝ラ','鍒嗘瀽鏁版嵁'], triggers:['瀹為獙鎺㈢┒','璁捐瀹為獙'], boundaries:['鎺у埗鍙橀噺'], examples:['鎽╂摝鍥犵礌'], tags:['瀹為獙'] },
      { id:'phy10', name:'鍏夊閫忛暅鎴愬儚', description:'鍑搁€忛暅鎴愬儚瑙勫緥鍙婂簲鐢?, subject:'physics', steps:['纭畾鐗╄窛鑼冨洿','瀵圭収鎴愬儚瑙勫緥','鍒ゆ柇鎴愬儚鐗圭偣'], triggers:['鍑搁€忛暅','鎴愬儚','鐒﹁窛'], boundaries:['鍒嗘竻瀹炶櫄鍍?], examples:['鍑搁€忛暅瀹為獙'], tags:['鍏夊','閫忛暅'] },
    ],
  },
  {
    id: 'chemistry-tutor',
    name: '鍖栫敓鎱?,
    title: '鍖栧鎺ㄧ悊鏁欑粌',
    description: '涓撴敾鍖栧鎺ㄧ悊涓庡疄楠岃璁★紝10涓妧鑳借鐩栫墿璐ㄦ帹鏂€佸疄楠屾帰绌躲€佸寲瀛﹁绠?,
    avatar: '馃敩',
    color: '#8B5CF6',
    skills: [
      { id:'chem01', name:'婧惰В搴︽洸绾夸笌婧舵恫璁＄畻', description:'婧惰В搴︽洸绾胯В璇诲拰娴撳害璁＄畻', subject:'chemistry', steps:['璇绘洸绾垮浘','鍒ゆ柇楗卞拰鍚?,'璁＄畻娴撳害'], triggers:['婧惰В搴?,'楗卞拰婧舵恫'], boundaries:['娉ㄦ剰娓╁害褰卞搷'], examples:['鏇茬嚎鍒嗘瀽'], tags:['婧惰В搴?,'婧舵恫'] },
      { id:'chem02', name:'鐗╄川鎺ㄦ柇涓庢鍥惧垎鏋?, description:'鏍规嵁瀹為獙鐜拌薄鎺ㄦ柇鐗╄川', subject:'chemistry', steps:['鎵剧獊鐮村彛','椤烘帹閫嗘帹','楠岃瘉鎵€鏈夋潯浠?], triggers:['鎺ㄦ柇棰?,'妗嗗浘','鐗╄川杞寲'], boundaries:['楠岃瘉姣忎釜鍙嶅簲'], examples:['妗嗗浘鎺ㄦ柇'], tags:['鎺ㄦ柇'] },
      { id:'chem03', name:'閲戝睘娲诲姩鎬т笌鎴愬垎鍒嗘瀽', description:'閲戝睘娲诲姩鎬ч『搴忓垽鏂拰搴旂敤', subject:'chemistry', steps:['鎺掓椿鍔ㄦ€ч『搴?,'鍒嗘瀽鑳藉惁鍙嶅簲','鍒ゆ柇浜х墿'], triggers:['閲戝睘娲诲姩鎬?,'缃崲'], boundaries:['娉ㄦ剰鐗规畩閲戝睘'], examples:['閲戝睘涓庣洂鍙嶅簲'], tags:['閲戝睘','娲诲姩鎬?] },
      { id:'chem04', name:'鍖栧鐢ㄨ涓庡厓绱犲懆鏈熻〃', description:'鍖栧悎浠峰寲瀛﹀紡鏂圭▼寮忕殑涔﹀啓', subject:'chemistry', steps:['纭畾鍖栧悎浠?,'鍐欏寲瀛﹀紡','閰嶅钩'], triggers:['鍖栧寮?,'鍖栧悎浠?,'閰嶅钩'], boundaries:['娉ㄦ剰鍙嶅簲鏉′欢'], examples:['閰嶅钩'], tags:['鍖栧鐢ㄨ'] },
      { id:'chem05', name:'閰哥⒈鐩愭€ц川涓庡弽搴?, description:'閰哥⒈鐩愬寲瀛︽€ц川鍙婂鍒嗚В鍙嶅簲', subject:'chemistry', steps:['鍒ゆ柇鐗╄川绫诲埆','棰勬祴鍙嶅簲','楠岃瘉鏉′欢'], triggers:['閰哥⒈涓拰','澶嶅垎瑙?,'pH'], boundaries:['闇€娌夋穩姘斾綋鎴栨按'], examples:['涓拰婊村畾'], tags:['閰?,'纰?,'鐩?] },
      { id:'chem06', name:'瀹為獙鎺㈢┒涓庢柟妗堣璁?, description:'鍖栧瀹為獙璁捐鐨勫熀鏈師鍒欐柟娉?, subject:'chemistry', steps:['鏄庣‘鐩殑','璁捐鏂规','棰勬祴鐜拌薄','鍒嗘瀽缁撴灉'], triggers:['瀹為獙鏂规','鎺㈢┒'], boundaries:['娉ㄦ剰瀹夊叏鐜繚'], examples:['鐕冪儳鏉′欢'], tags:['瀹為獙'] },
      { id:'chem07', name:'鐗╄川閴村埆妫€楠屼笌闄ゆ潅', description:'甯歌鐗╄川鐨勯壌鍒拰鎻愮函鏂规硶', subject:'chemistry', steps:['鍒嗘瀽鐗╄川宸紓','閫夐壌鍒瘯鍓?,'鎻忚堪鐜拌薄'], triggers:['閴村埆','妫€楠?,'闄ゆ潅'], boundaries:['闇€鏄庢樉涓嶅悓鐜拌薄'], examples:['姘斾綋閴村埆'], tags:['閴村埆','闄ゆ潅'] },
      { id:'chem08', name:'鍥惧儚鍒嗘瀽', description:'pH鏇茬嚎娌夋穩鏇茬嚎绛夊浘鍍忓垎鏋?, subject:'chemistry', steps:['鐪嬫竻鍧愭爣','鍒嗘瀽鍏抽敭鐐?,'瑙ｉ噴鍙樺寲鍘熷洜'], triggers:['鍥惧儚','鏇茬嚎'], boundaries:['娉ㄦ剰鍧愭爣绯诲惈涔?], examples:['涓拰鏇茬嚎'], tags:['鍥惧儚'] },
      { id:'chem09', name:'鍖栧璁＄畻', description:'鏍规嵁鍖栧鏂圭▼寮忕殑璁＄畻', subject:'chemistry', steps:['鍐欐柟绋嬪紡','鏍囧凡鐭ユ湭鐭?,'鍒楁瘮渚嬫眰瑙?], triggers:['璁＄畻棰?,'璐ㄩ噺鍒嗘暟'], boundaries:['鐩稿鍒嗗瓙璐ㄩ噺绠楀'], examples:['鏂圭▼寮忚绠?], tags:['璁＄畻'] },
      { id:'chem10', name:'鍖栧涓庣敓娲?, description:'鍖栧鍦ㄧ敓娲讳腑鐨勫簲鐢?, subject:'chemistry', steps:['鑱旂郴鐢熸椿','鍖归厤鍖栧鍘熺悊','鍒嗘瀽鍒╁紛'], triggers:['鍖栧涓庣敓娲?,'鏉愭枡','鐜繚'], boundaries:['缁撳悎瀹為檯'], examples:['鍚堟垚鏉愭枡'], tags:['鐢熸椿','搴旂敤'] },
    ],
  },
  {
    id: 'chinese-tutor',
    name: '鏂囧績闆?,
    title: '璇枃闃呰鏁欑粌',
    description: '涓撴敾璇枃闃呰涓庡啓浣滐紝10涓妧鑳借鐩栬鍙欐枃璇存槑鏂囪璁烘枃鏂囪█鏂囦綔鏂?,
    avatar: '馃摉',
    color: '#F59E0B',
    skills: [
      { id:'chi01', name:'璁板彊鏂囬槄璇?浜虹墿涓庢儏鑺?, description:'浜虹墿褰㈣薄鍒嗘瀽鍜屾儏鑺傜粨鏋勬鎷?, subject:'chinese', steps:['鎵惧嚭鎻忓啓璇彞','鍒嗘瀽鎬ф牸','姒傛嫭鎯呰妭'], triggers:['浜虹墿褰㈣薄','鎬ф牸','鎯呰妭'], boundaries:['鍩轰簬鏂囨湰'], examples:['鏁呬埂鍒嗘瀽'], tags:['璁板彊鏂?,'浜虹墿'] },
      { id:'chi02', name:'璁板彊鏂囬槄璇?鍙ュ瓙璧忔瀽', description:'淇緸鎻忓啓鐢ㄨ瘝瑙掑害璧忔瀽鍙ュ瓙', subject:'chinese', steps:['鍒ゆ柇鎵嬫硶','鍒嗘瀽鏁堟灉','鑱旂郴鎯呮劅'], triggers:['璧忔瀽','琛ㄨ揪鏁堟灉','淇緸'], boundaries:['涓嶈劚绂绘枃鏈?], examples:['璧忔瀽妯℃澘'], tags:['璁板彊鏂?,'璧忔瀽'] },
      { id:'chi03', name:'璇存槑鏂囬槄璇?, description:'璇存槑鏂囩殑缁撴瀯鏂规硶鍜岃瑷€鐗圭偣', subject:'chinese', steps:['璇嗗埆鏂规硶','鍒嗘瀽椤哄簭','浣撲細璇█'], triggers:['璇存槑鏂规硶','璇存槑椤哄簭'], boundaries:['鍖哄垎涓嶅悓鏂规硶'], examples:['浜嬬墿璇存槑鏂?], tags:['璇存槑鏂?] },
      { id:'chi04', name:'璁鏂囬槄璇?, description:'璁虹偣璁烘嵁璁鸿瘉涓夎绱犲垎鏋?, subject:'chinese', steps:['鎵句腑蹇冭鐐?,'鍒嗘瀽璁烘嵁绫诲瀷','鍒ゆ柇璁鸿瘉鏂规硶'], triggers:['璁虹偣','璁烘嵁','璁鸿瘉'], boundaries:['鍖哄垎涓績璁虹偣鍜屽垎璁虹偣'], examples:['璁鸿瘉缁撴瀯'], tags:['璁鏂?] },
      { id:'chi05', name:'闈炶繛缁€ф枃鏈?, description:'鍥捐〃鏁版嵁澶氭潗鏂欐枃鏈暣鍚堝垎鏋?, subject:'chinese', steps:['鎻愬彇鍏抽敭淇℃伅','瀵规瘮寮傚悓','寰楃粨璁?], triggers:['闈炶繛缁€ф枃鏈?,'澶氭潗鏂?], boundaries:['娉ㄦ剰鏁版嵁鍏崇郴'], examples:['鍥捐〃鍒嗘瀽'], tags:['闈炶繛鏂囨湰'] },
      { id:'chi06', name:'鏂囪█鏂囬槄璇?, description:'瀹炶瘝铏氳瘝杈ㄦ瀽鍜屽彞瀛愮炕璇?, subject:'chinese', steps:['鎺ㄦ柇瀹炶瘝','杈ㄦ瀽铏氳瘝','閫愬瓧缈昏瘧'], triggers:['瀹炶瘝','铏氳瘝','缈昏瘧'], boundaries:['娉ㄦ剰鍙や粖寮備箟'], examples:['鍑哄笀琛?], tags:['鏂囪█鏂?] },
      { id:'chi07', name:'鍙よ瘲璇嶉壌璧?, description:'鎰忚薄鎯呮劅鍜岃〃鐜版墜娉曞垎鏋?, subject:'chinese', steps:['鎵炬剰璞?,'鍒嗘瀽鎰忓','璇嗗埆鎵嬫硶','浣撲細鎯呮劅'], triggers:['鎰忚薄','鎯呮劅','鎵嬫硶'], boundaries:['鐭ヤ汉璁轰笘'], examples:['鏉滅敨璇楁瓕'], tags:['鍙よ瘲璇?] },
      { id:'chi08', name:'鍩虹绉疮涓庣梾鍙?, description:'瀛楅煶瀛楀舰鎴愯鐥呭彞淇敼', subject:'chinese', steps:['绉疮鏄撻敊瀛?,'鎴愯杈ㄤ箟','鎵剧梾鍙ョ被鍨?,'淇敼'], triggers:['鐥呭彞','鎴愯','瀛楀舰'], boundaries:['鐥呭彞绫诲瀷瑕佸噯纭?], examples:['鎼厤涓嶅綋'], tags:['鍩虹','鐥呭彞'] },
      { id:'chi09', name:'鐜颁唬鏂囧啓浣?, description:'瀹￠绔嬫剰缁撴瀯鍜岀礌鏉愯繍鐢?, subject:'chinese', steps:['瀹℃竻棰樼洰','纭畾绔嬫剰','鎼粨鏋?,'濉厖绱犳潗'], triggers:['浣滄枃','绔嬫剰','缁撴瀯'], boundaries:['绔嬫剰瑕佹繁鍒讳笉鍋忛'], examples:['鍛介浣滄枃'], tags:['鍐欎綔'] },
      { id:'chi10', name:'涓€冧綔鏂囨娂棰?, description:'鐑偣绱犳潗绉疮鍜屾娂棰樻柟鍚?, subject:'chinese', steps:['绉疮鐑偣','澶氳搴﹁繍鐢?,'缁冪湡棰?], triggers:['绱犳潗','鎶奸','鐑偣'], boundaries:['绱犳潗瑕佺伒娲?], examples:['AI鏃朵唬绱犳潗'], tags:['绱犳潗','鎶奸'] },
    ],
  },
  {
    id: 'english-tutor',
    name: '璇€氳、',
    title: '鑻辫瀹炴垬鏁欑粌',
    description: '涓撴敾鑻辫涓€冨疄鎴橈紝10涓妧鑳借鐩栭槄璇诲畬褰㈣娉曞啓浣滆瘝姹?,
    avatar: '馃實',
    color: '#EC4899',
    skills: [
      { id:'eng01', name:'闃呰鐞嗚В-缁嗚妭涓庢帹鏂?, description:'缁嗚妭棰樺拰鎺ㄦ柇棰樿В棰樻柟娉?, subject:'english', steps:['璇婚骞插垝璇?,'鍘熸枃瀹氫綅','瀵规瘮閫夐」','鎺掗櫎骞叉壈'], triggers:['缁嗚妭棰?,'鎺ㄦ柇棰?], boundaries:['涓嶈杩囧害鎺ㄧ悊'], examples:['浜虹墿浼犺'], tags:['闃呰','缁嗚妭'] },
      { id:'eng02', name:'闃呰鐞嗚В-涓绘棬涓庣粨鏋?, description:'涓绘棬澶ф剰棰樺拰绡囩珷缁撴瀯棰?, subject:'english', steps:['蹇€熸祻瑙?,'褰掔撼涓绘棬','鍒嗘瀽缁撴瀯'], triggers:['涓绘棬','鏍囬','缁撴瀯'], boundaries:['涓绘棬瑕佽鐩栧叏鏂?], examples:['璇存槑鏂囦富鏃?], tags:['闃呰','涓绘棬'] },
      { id:'eng03', name:'瀹屽舰濉┖', description:'涓婁笅鏂囬€昏緫鍒嗘瀽鍜屽浐瀹氭惌閰?, subject:'english', steps:['閫氳鍏ㄦ枃','閫愮┖鍒嗘瀽','妫€鏌ヤ竴鑷存€?], triggers:['瀹屽舰濉┖','涓婁笅鏂?], boundaries:['鍏堥€氳鍐嶅～绌?], examples:['璁板彊鏂囧畬褰?], tags:['瀹屽舰'] },
      { id:'eng04', name:'璇硶濉┖', description:'璇嶆€ц浆鎹㈠拰鏃舵€佽鎬佹妧宸?, subject:'english', steps:['鍒ゆ柇璇嶆€?,'鑰冭檻鏃舵€?,'鍐欐纭舰寮?], triggers:['璇硶濉┖','璇嶆€ц浆鎹?], boundaries:['娉ㄦ剰涓嶈鍒欏彉鍖?], examples:['鍔ㄨ瘝鏃舵€?], tags:['璇硶'] },
      { id:'eng05', name:'鐭枃杩樺師', description:'涓冮€変簲鐭枃杩樺師瑙ｉ鏂规硶', subject:'english', steps:['璇婚€夐」澶ф剰','鍒嗘瀽閫昏緫鍏崇郴','浠ｅ叆妫€鏌?], triggers:['鐭枃杩樺師','涓冮€変簲'], boundaries:['娉ㄦ剰浠ｈ瘝杩炶瘝鎻愮ず'], examples:['涓冮€変簲'], tags:['杩樺師'] },
      { id:'eng06', name:'鏃舵€佽鎬?, description:'鍏ぇ鏃舵€佸拰琚姩璇€佽鲸鏋?, subject:'english', steps:['鎵炬椂闂寸姸璇?,'瀹氭椂鎬?,'鍒ゆ柇涓昏鍔?], triggers:['鏃舵€?,'璇€?,'琚姩'], boundaries:['娉ㄦ剰涓€鑷存€?], examples:['鐜板湪瀹屾垚鏃?], tags:['鏃舵€?,'璇€?] },
      { id:'eng07', name:'浠庡彞鍒嗘瀽', description:'瀹句粠瀹氫粠鐘朵粠鐨勮鲸鏋?, subject:'english', steps:['鎵捐繛鎺ヨ瘝','鍒嗘瀽浠庡彞绫诲瀷','鍒ゆ柇鎴愬垎'], triggers:['浠庡彞','瀹捐浠庡彞','瀹氳浠庡彞'], boundaries:['鍖哄垎that鐢ㄦ硶'], examples:['瀹氳浠庡彞'], tags:['浠庡彞'] },
      { id:'eng08', name:'璇嶆硶杈ㄦ瀽', description:'鏄撴贩璇嶆眹杈ㄦ瀽鍜岄€夎瘝濉┖', subject:'english', steps:['杈ㄦ瀽璇嶄箟鍖哄埆','鑰冭檻鎼厤','閫夋渶鍚堥€?], triggers:['杈ㄦ瀽','鏄撴贩璇?,'閫夎瘝'], boundaries:['娉ㄦ剰鍥哄畾鎼厤'], examples:['spend/cost'], tags:['璇嶆眹','杈ㄦ瀽'] },
      { id:'eng09', name:'涔﹂潰琛ㄨ揪', description:'涓€冭嫳璇綔鏂囨ā鏉挎柟娉?, subject:'english', steps:['瀹￠鍒楁彁绾?,'濂楁ā鏉挎鏋?,'濉厖鍐呭','妫€鏌?], triggers:['浣滄枃','涔﹂潰琛ㄨ揪'], boundaries:['鐏垫椿鍙橀€?], examples:['寤鸿淇?], tags:['鍐欎綔','妯℃澘'] },
      { id:'eng10', name:'璇嶆眹鎷撳睍', description:'璇嶆牴璇嶇紑娉曟墿灞曡瘝姹?, subject:'english', steps:['璇嗗埆璇嶆牴','鍒ゆ柇璇嶇紑','鎺ㄦ祴璇嶄箟'], triggers:['鑳屽崟璇?,'璇嶆牴','璇嶆眹閲?], boundaries:['鐗规畩鍚箟闇€鍗曠嫭璁?], examples:['un/dis/in'], tags:['璇嶆眹','璇嶆牴'] },
    ],
  },
  {
    id: 'study-method-tutor',
    name: '绛栨棤閬?,
    title: '瀛︿範鏂规硶绛栫暐鏁欑粌',
    description: '涓撴敾瀛︿範绛栫暐涓庡簲璇曟柟娉曪紝8涓ā鍧楄鐩栨彁鍒嗗垎鏋愩€佺摱棰堢獊鐮淬€佽€冭瘯鎶㈠垎',
    avatar: '馃幆',
    color: '#14B8A6',
    skills: [
      { id:'met01', name:'鎶曞叆浜у嚭鍒嗘瀽', description:'鍒嗘瀽鍚勭鎻愬垎鎬т环姣?, subject:'method', steps:['缁熻褰撳墠姘村钩','鍒嗘瀽鎻愬垎娼滃姏','纭畾浼樺厛绾?,'鍒跺畾鏂规'], triggers:['鎬庝箞鎻愬垎鏈€蹇?,'鏃堕棿涓嶅'], boundaries:['涓嶆帹鑽愮殑绉戜篃瑕佷繚鍩虹'], examples:['3涓湀鏃堕棿鍒嗛厤'], tags:['鎻愬垎','鏁堢巼'] },
      { id:'met02', name:'鐡堕鏈熷鐞?, description:'鎴愮哗涓嶆彁鍗囩殑鍘熷洜鍒嗘瀽鍜岀獊鐮?, subject:'method', steps:['璇婃柇褰撳墠鐘舵€?,'鎵剧摱棰堝師鍥?,'璋冩暣绛栫暐','瀹炴柦'], triggers:['鎴愮哗涓嶅姩','鐡堕','娌¤繘姝?], boundaries:['闇€鍧氭寔2鍛?], examples:['鏁板120涓婁笉鍘?], tags:['鐡堕','绐佺牬'] },
      { id:'met03', name:'鑰冭瘯鎶㈠垎', description:'鑰冨満鏃堕棿鍒嗛厤绛旈椤哄簭妫€鏌ユ妧宸?, subject:'method', steps:['閫熻瀹氱瓥鐣?,'鍏堟槗鍚庨毦','闅鹃鏈夐妗?,'鐣欐椂闂存鏌?], triggers:['鑰冭瘯绱у紶','鍋氫笉瀹?,'绮楀績'], boundaries:['闅鹃涓嶈秴15鍒嗛挓'], examples:['鍚勭鏃堕棿鍒嗛厤'], tags:['鑰冭瘯','鎶€宸?] },
      { id:'met04', name:'鐭ヨ瘑璁板繂鏂规硶', description:'楂樻晥璁板繂鏂规硶锛氳壘瀹炬旦鏂€濈淮瀵煎浘', subject:'method', steps:['鐞嗚В鏈川','鏋勫缓妗嗘灦','鐢ㄦ妧宸?,'瀹氭湡澶嶄範'], triggers:['璁颁笉浣?,'鑳屼簡灏卞繕'], boundaries:['鐞嗚В鏄墠鎻?], examples:['鍖栧鏂圭▼寮忚蹇?], tags:['璁板繂','鏂规硶'] },
      { id:'met05', name:'鍒烽鏁堢巼', description:'绮惧埛vs棰樻捣銆侀敊棰樻湰鏂规硶', subject:'method', steps:['閫夊ソ棰?,'闄愭椂鍋?,'瀵圭瓟妗?,'鎬荤粨閿欏洜'], triggers:['鍒烽','棰樻捣','閿欓鏈?], boundaries:['閲嶈川閲忎笉閲嶆暟閲?], examples:['閿欓鏈ā鏉?], tags:['鍒烽','鏁堢巼'] },
      { id:'met06', name:'瀛︾濂楄矾', description:'鍚勭甯歌棰樺瀷鍜岃В棰樺璺?, subject:'method', steps:['璇嗗埆棰樺瀷','鍖归厤濂楄矾','鐏垫椿杩愮敤'], triggers:['濂楄矾','妯℃澘','鍥哄畾棰樺瀷'], boundaries:['濂楄矾涓嶆浛浠ｇ悊瑙?], examples:['鍘嬭酱棰樺璺?], tags:['濂楄矾','棰樺瀷'] },
      { id:'met07', name:'瀛︿範鍔ㄥ姏', description:'鍔ㄥ姏涓嶈冻鍒嗘瀽鍜屾縺鍔辨柟娉?, subject:'method', steps:['鍒嗘瀽鍘熷洜','璁剧洰鏍?,'寤哄弽棣?,'鍏讳範鎯?], triggers:['涓嶆兂瀛?,'娌″姩鍔?,'鎷栧欢'], boundaries:['闇€鎵惧埌鍐呭湪鍔ㄥ姏'], examples:['姣忔棩灏忕洰鏍?], tags:['鍔ㄥ姏','蹇冩€?] },
      { id:'met08', name:'蹇楁効濉姤', description:'涓€冨織鎰垮～鎶ョ瓥鐣?, subject:'method', steps:['浜嗚В鍒嗘暟绾?,'璇勪及姘村钩','瀹氱瓥鐣?,'纭濉姤'], triggers:['蹇楁効','濉織鎰?,'閫夊鏍?], boundaries:['淇濆畧杩樻槸鍐茶缁撳悎鑷韩'], examples:['姊害濉姤'], tags:['蹇楁効','濉姤'] },
    ],
  },
];

export const SUBJECTS = [
  { id:'math', label:'鏁板', icon:'馃搻', agentId:'math-tutor' },
  { id:'physics', label:'鐗╃悊', icon:'鈿?, agentId:'physics-tutor' },
  { id:'chemistry', label:'鍖栧', icon:'馃敩', agentId:'chemistry-tutor' },
  { id:'chinese', label:'璇枃', icon:'馃摉', agentId:'chinese-tutor' },
  { id:'english', label:'鑻辫', icon:'馃實', agentId:'english-tutor' },
  { id:'method', label:'瀛︿範鏂规硶', icon:'馃幆', agentId:'study-method-tutor' },
];

export const PRICING_PLANS = [
  { id:'free', name:'免费体验', price:0, period:'永久', description:'每日30次提问', features:['每日30次对话', '1000积分', '基础AI回答'], popular:false, dailyLimit:30, credits:1000 },
  { id:'monthly', name:'月度会员', price:39, period:'月', description:'不限对话次数', features:['不限对话次数', '全科6位AI专家', '技能地图'], popular:false, dailyLimit:-1, credits:0 },
  { id:'yearly', name:'年度会员', price:299, period:'年', description:'不限对话+赠送积分', features:['不限对话次数', '全科6位AI专家', '技能地图', '赠送5000积分', '学情诊断', '优先更新'], popular:true, dailyLimit:-1, credits:5000 },
];

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';