import { Agent, Skill } from '@/types';

export const APP_NAME = '中考提分 AI 私教';
export const APP_DESC = '6 位 AI 专家 · 55 个核心技能 · 专属中考私教';

export const AGENTS: Agent[] = [
  {
    id: 'math-tutor',
    name: '算无遗',
    title: '数学压轴教练',
    description: '专攻中考数学压轴题，14个技能覆盖二次函数、几何构造、分类讨论等类型',
    avatar: '📐',
    color: '#3B82F6',
    skills: [
      { id:'math01', name:'二次函数最值与范围分析', description:'定轴定区间/定轴动区间/动轴定区间三种场景', subject:'math', steps:['配方化顶点式','判断场景类型','按场景执行','验证合理性'], triggers:['最大值是顶点吗','什么时候看端点','对称轴位置'], boundaries:['无区间限制不用','一次函数不用'], examples:['2024T22票价','2023菱形面积'], tags:['二次函数','最值'] },
      { id:'math02', name:'压轴题综合破解思路', description:'读题-定位-破局三步法拆解压轴题', subject:'math', steps:['读题划关键','定位知识点','选切入点','分步推进','验证'], triggers:['完全没思路','不知道从哪下手'], boundaries:['简单题不需要'], examples:['2024压轴题'], tags:['压轴题','策略'] },
      { id:'math03', name:'分类讨论思想', description:'参数讨论、图形位置讨论的系统方法论', subject:'math', steps:['确定分类标准','穷举所有情况','分别求解','合并结果'], triggers:['需要分类讨论吗','分几种情况'], boundaries:['不可遗漏情况'], examples:['动点问题'], tags:['分类讨论'] },
      { id:'math04', name:'存在性问题分类讨论', description:'判断是否存在点/线段满足条件', subject:'math', steps:['假设存在','建立方程','求解验证','下结论'], triggers:['是否存在这样的点','是否可能'], boundaries:['验证解在范围内'], examples:['存在点P'], tags:['存在性'] },
      { id:'math05', name:'新定义运算与规则', description:'自定义运算符号和规则的理解应用', subject:'math', steps:['理解新定义','转化为常规运算','执行计算','验证'], triggers:['定义新运算','规定'], boundaries:['严格遵守定义'], examples:['新定义题'], tags:['新定义'] },
      { id:'math06', name:'三段式推理', description:'因为→所以→因此的数学证明框架', subject:'math', steps:['明确已知','逐层推导','得结论'], triggers:['证明题','求证'], boundaries:['每一步要有依据'], examples:['几何证明'], tags:['推理'] },
      { id:'math07', name:'旋转构造全等模型', description:'旋转变换构造全等三角形', subject:'math', steps:['识别旋转中心','确定旋转角度','构造全等','利用性质求解'], triggers:['旋转','转动','绕点'], boundaries:['注意旋转方向'], examples:['旋转构造'], tags:['旋转','全等'] },
      { id:'math08', name:'辅助线添加技巧', description:'倍长中线、截长补短、作平行等', subject:'math', steps:['观察图形特征','选辅助线类型','添加辅助线','利用新图形求解'], triggers:['要做辅助线吗','怎么加'], boundaries:['辅助线不是越多越好'], examples:['倍长中线'], tags:['辅助线'] },
      { id:'math09', name:'圆模型综合', description:'垂径定理、圆周角定理、切线性质等', subject:'math', steps:['识别圆元素','提取圆的性质','结合其他图形求解'], triggers:['圆','圆周角','切线'], boundaries:['注意直径对直角'], examples:['圆与三角形'], tags:['圆'] },
      { id:'math10', name:'相似模型综合', description:'A字型、8字型、K字型相似模型', subject:'math', steps:['找对应角','确定相似比','列比例式','求解'], triggers:['相似','对应成比例'], boundaries:['对应边要对应好'], examples:['A字型相似'], tags:['相似'] },
      { id:'math11', name:'最短路径与最值问题', description:'将军饮马、胡不归、阿氏圆等最值模型', subject:'math', steps:['识别最值模型','作对称点','连接求解'], triggers:['最短','最小','最大距离'], boundaries:['不同模型用不同方法'], examples:['将军饮马'], tags:['最值','路径'] },
      { id:'math12', name:'一题多解与解法对比', description:'从代数、几何、函数多角度求解', subject:'math', steps:['找代数特征','找几何特征','选最优解法'], triggers:['有其他解法吗','哪种更好'], boundaries:['比较优劣'], examples:['代数几何双解'], tags:['多解'] },
      { id:'math13', name:'特殊到一般归纳法', description:'从特殊情形找规律，推广到一般结论', subject:'math', steps:['取特殊值','观察规律','推广到一般','证明'], triggers:['找规律','猜想'], boundaries:['需证明一般结论'], examples:['数列规律'], tags:['归纳'] },
      { id:'math14', name:'中点与角平分线模型', description:'中点和角平分线的性质与应用', subject:'math', steps:['识别中点或角平分线','应用性质','结合条件求解'], triggers:['中点','角平分线'], boundaries:['注意中位线条件'], examples:['中点四边形'], tags:['中点','角平分线'] },
    ],
  },
  {
    id: 'physics-tutor',
    name: '力拔山',
    title: '物理实验教练',
    description: '专攻物理压轴题与实验探究，10个技能覆盖力学、电学、光学全部重点',
    avatar: '⚡',
    color: '#10B981',
    skills: [
      { id:'phy01', name:'压强浮力综合模型', description:'固体液体压强与浮力的综合计算', subject:'physics', steps:['状态判定','受力分析','公式展开','连锁推导','验证'], triggers:['压强和浮力','沉底漂浮'], boundaries:['纯电学不用'], examples:['2024压轴题'], tags:['压强','浮力'] },
      { id:'phy02', name:'动态电路极值分析', description:'滑变移动引起的电流电压功率变化', subject:'physics', steps:['分析电路结构','确定滑变范围','计算极值'], triggers:['滑片移动','最大功率'], boundaries:['确认串联并联'], examples:['滑变最值'], tags:['电路','极值'] },
      { id:'phy03', name:'杠杆滑轮组综合', description:'杠杆平衡和滑轮组受力的综合计算', subject:'physics', steps:['确定支点','分析力臂','列平衡方程','求解'], triggers:['杠杆','滑轮'], boundaries:['注意绳子段数'], examples:['杠杆滑轮组合'], tags:['杠杆','滑轮'] },
      { id:'phy04', name:'能源计算专题', description:'功、功率、机械效率、能量转化计算', subject:'physics', steps:['确定能量形式','列能量公式','代入数据'], triggers:['效率','功率','做功'], boundaries:['注意单位换算'], examples:['机械效率'], tags:['能源','效率'] },
      { id:'phy05', name:'电学综合计算', description:'欧姆定律、电功率、焦耳定律综合应用', subject:'physics', steps:['画等效电路','标已知量','选公式求解'], triggers:['电功率','欧姆定律'], boundaries:['区分纯电阻'], examples:['多挡位用电器'], tags:['电学','功率'] },
      { id:'phy06', name:'浮力多状态计算', description:'同一物体在不同状态下的浮力分析', subject:'physics', steps:['分析各状态','列平衡方程组','联立求解'], triggers:['漂浮悬浮','沉底'], boundaries:['不同状态分别分析'], examples:['一物多状态'], tags:['浮力','多状态'] },
      { id:'phy07', name:'物理估测与常识', description:'常见物理量的估测值', subject:'physics', steps:['回忆常见值','对比选项','排除不合理'], triggers:['估测','最接近'], boundaries:['记住标准值'], examples:['教室高度'], tags:['估测'] },
      { id:'phy08', name:'物理多选题破解', description:'多选审题和排除法技巧', subject:'physics', steps:['审题干陷阱','逐个选项分析','排除明显错'], triggers:['多选题','以下正确的'], boundaries:['宁少选不错选'], examples:['声现象多选'], tags:['多选'] },
      { id:'phy09', name:'物理实验探究', description:'控制变量法、转换法等实验方法', subject:'physics', steps:['明确实验目的','选实验方法','设计步骤','分析数据'], triggers:['实验探究','设计实验'], boundaries:['控制变量'], examples:['摩擦因素'], tags:['实验'] },
      { id:'phy10', name:'光学透镜成像', description:'凸透镜成像规律及应用', subject:'physics', steps:['确定物距范围','对照成像规律','判断成像特点'], triggers:['凸透镜','成像','焦距'], boundaries:['分清实虚像'], examples:['凸透镜实验'], tags:['光学','透镜'] },
    ],
  },
  {
    id: 'chemistry-tutor',
    name: '化生慧',
    title: '化学推理教练',
    description: '专攻化学推理与实验设计，10个技能覆盖物质推断、实验探究、化学计算',
    avatar: '🔬',
    color: '#8B5CF6',
    skills: [
      { id:'chem01', name:'溶解度曲线与溶液计算', description:'溶解度曲线解读和浓度计算', subject:'chemistry', steps:['读曲线图','判断饱和否','计算浓度'], triggers:['溶解度','饱和溶液'], boundaries:['注意温度影响'], examples:['曲线分析'], tags:['溶解度','溶液'] },
      { id:'chem02', name:'物质推断与框图分析', description:'根据实验现象推断物质', subject:'chemistry', steps:['找突破口','顺推逆推','验证所有条件'], triggers:['推断题','框图','物质转化'], boundaries:['验证每个反应'], examples:['框图推断'], tags:['推断'] },
      { id:'chem03', name:'金属活动性与成分分析', description:'金属活动性顺序判断和应用', subject:'chemistry', steps:['排活动性顺序','分析能否反应','判断产物'], triggers:['金属活动性','置换'], boundaries:['注意特殊金属'], examples:['金属与盐反应'], tags:['金属','活动性'] },
      { id:'chem04', name:'化学用语与元素周期表', description:'化合价化学式方程式的书写', subject:'chemistry', steps:['确定化合价','写化学式','配平'], triggers:['化学式','化合价','配平'], boundaries:['注意反应条件'], examples:['配平'], tags:['化学用语'] },
      { id:'chem05', name:'酸碱盐性质与反应', description:'酸碱盐化学性质及复分解反应', subject:'chemistry', steps:['判断物质类别','预测反应','验证条件'], triggers:['酸碱中和','复分解','pH'], boundaries:['需沉淀气体或水'], examples:['中和滴定'], tags:['酸','碱','盐'] },
      { id:'chem06', name:'实验探究与方案设计', description:'化学实验设计的基本原则方法', subject:'chemistry', steps:['明确目的','设计方案','预测现象','分析结果'], triggers:['实验方案','探究'], boundaries:['注意安全环保'], examples:['燃烧条件'], tags:['实验'] },
      { id:'chem07', name:'物质鉴别检验与除杂', description:'常见物质的鉴别和提纯方法', subject:'chemistry', steps:['分析物质差异','选鉴别试剂','描述现象'], triggers:['鉴别','检验','除杂'], boundaries:['需明显不同现象'], examples:['气体鉴别'], tags:['鉴别','除杂'] },
      { id:'chem08', name:'图像分析', description:'pH曲线沉淀曲线等图像分析', subject:'chemistry', steps:['看清坐标','分析关键点','解释变化原因'], triggers:['图像','曲线'], boundaries:['注意坐标系含义'], examples:['中和曲线'], tags:['图像'] },
      { id:'chem09', name:'化学计算', description:'根据化学方程式的计算', subject:'chemistry', steps:['写方程式','标已知未知','列比例求解'], triggers:['计算题','质量分数'], boundaries:['相对分子质量算对'], examples:['方程式计算'], tags:['计算'] },
      { id:'chem10', name:'化学与生活', description:'化学在生活中的应用', subject:'chemistry', steps:['联系生活','匹配化学原理','分析利弊'], triggers:['化学与生活','材料','环保'], boundaries:['结合实际'], examples:['合成材料'], tags:['生活','应用'] },
    ],
  },
  {
    id: 'chinese-tutor',
    name: '文心雕',
    title: '语文阅读教练',
    description: '专攻语文阅读与写作，10个技能覆盖记叙文说明文议论文文言文作文',
    avatar: '📖',
    color: '#F59E0B',
    skills: [
      { id:'chi01', name:'记叙文阅读-人物与情节', description:'人物形象分析和情节结构概括', subject:'chinese', steps:['找出描写语句','分析性格','概括情节'], triggers:['人物形象','性格','情节'], boundaries:['基于文本'], examples:['故乡分析'], tags:['记叙文','人物'] },
      { id:'chi02', name:'记叙文阅读-句子赏析', description:'修辞描写用词角度赏析句子', subject:'chinese', steps:['判断手法','分析效果','联系情感'], triggers:['赏析','表达效果','修辞'], boundaries:['不脱离文本'], examples:['赏析模板'], tags:['记叙文','赏析'] },
      { id:'chi03', name:'说明文阅读', description:'说明文的结构方法和语言特点', subject:'chinese', steps:['识别方法','分析顺序','体会语言'], triggers:['说明方法','说明顺序'], boundaries:['区分不同方法'], examples:['事物说明文'], tags:['说明文'] },
      { id:'chi04', name:'议论文阅读', description:'论点论据论证三要素分析', subject:'chinese', steps:['找中心论点','分析论据类型','判断论证方法'], triggers:['论点','论据','论证'], boundaries:['区分中心论点和分论点'], examples:['论证结构'], tags:['议论文'] },
      { id:'chi05', name:'非连续性文本', description:'图表数据多材料文本整合分析', subject:'chinese', steps:['提取关键信息','对比异同','得结论'], triggers:['非连续性文本','多材料'], boundaries:['注意数据关系'], examples:['图表分析'], tags:['非连文本'] },
      { id:'chi06', name:'文言文阅读', description:'实词虚词辨析和句子翻译', subject:'chinese', steps:['推断实词','辨析虚词','逐字翻译'], triggers:['实词','虚词','翻译'], boundaries:['注意古今异义'], examples:['出师表'], tags:['文言文'] },
      { id:'chi07', name:'古诗词鉴赏', description:'意象情感和表现手法分析', subject:'chinese', steps:['找意象','分析意境','识别手法','体会情感'], triggers:['意象','情感','手法'], boundaries:['知人论世'], examples:['杜甫诗歌'], tags:['古诗词'] },
      { id:'chi08', name:'基础积累与病句', description:'字音字形成语病句修改', subject:'chinese', steps:['积累易错字','成语辨义','找病句类型','修改'], triggers:['病句','成语','字形'], boundaries:['病句类型要准确'], examples:['搭配不当'], tags:['基础','病句'] },
      { id:'chi09', name:'现代文写作', description:'审题立意结构和素材运用', subject:'chinese', steps:['审清题目','确定立意','搭结构','填充素材'], triggers:['作文','立意','结构'], boundaries:['立意要深刻不偏题'], examples:['命题作文'], tags:['写作'] },
      { id:'chi10', name:'中考作文押题', description:'热点素材积累和押题方向', subject:'chinese', steps:['积累热点','多角度运用','练真题'], triggers:['素材','押题','热点'], boundaries:['素材要灵活'], examples:['AI时代素材'], tags:['素材','押题'] },
    ],
  },
  {
    id: 'english-tutor',
    name: '语通衢',
    title: '英语实战教练',
    description: '专攻英语中考实战，10个技能覆盖阅读完形语法写作词汇',
    avatar: '🌍',
    color: '#EC4899',
    skills: [
      { id:'eng01', name:'阅读理解-细节与推断', description:'细节题和推断题解题方法', subject:'english', steps:['读题干划词','原文定位','对比选项','排除干扰'], triggers:['细节题','推断题'], boundaries:['不要过度推理'], examples:['人物传记'], tags:['阅读','细节'] },
      { id:'eng02', name:'阅读理解-主旨与结构', description:'主旨大意题和篇章结构题', subject:'english', steps:['快速浏览','归纳主旨','分析结构'], triggers:['主旨','标题','结构'], boundaries:['主旨要覆盖全文'], examples:['说明文主旨'], tags:['阅读','主旨'] },
      { id:'eng03', name:'完形填空', description:'上下文逻辑分析和固定搭配', subject:'english', steps:['通读全文','逐空分析','检查一致性'], triggers:['完形填空','上下文'], boundaries:['先通读再填空'], examples:['记叙文完形'], tags:['完形'] },
      { id:'eng04', name:'语法填空', description:'词性转换和时态语态技巧', subject:'english', steps:['判断词性','考虑时态','写正确形式'], triggers:['语法填空','词性转换'], boundaries:['注意不规则变化'], examples:['动词时态'], tags:['语法'] },
      { id:'eng05', name:'短文还原', description:'七选五短文还原解题方法', subject:'english', steps:['读选项大意','分析逻辑关系','代入检查'], triggers:['短文还原','七选五'], boundaries:['注意代词连词提示'], examples:['七选五'], tags:['还原'] },
      { id:'eng06', name:'时态语态', description:'八大时态和被动语态辨析', subject:'english', steps:['找时间状语','定时态','判断主被动'], triggers:['时态','语态','被动'], boundaries:['注意一致性'], examples:['现在完成时'], tags:['时态','语态'] },
      { id:'eng07', name:'从句分析', description:'宾从定从状从的辨析', subject:'english', steps:['找连接词','分析从句类型','判断成分'], triggers:['从句','宾语从句','定语从句'], boundaries:['区分that用法'], examples:['定语从句'], tags:['从句'] },
      { id:'eng08', name:'词法辨析', description:'易混词汇辨析和选词填空', subject:'english', steps:['辨析词义区别','考虑搭配','选最合适'], triggers:['辨析','易混词','选词'], boundaries:['注意固定搭配'], examples:['spend/cost'], tags:['词汇','辨析'] },
      { id:'eng09', name:'书面表达', description:'中考英语作文模板方法', subject:'english', steps:['审题列提纲','套模板框架','填充内容','检查'], triggers:['作文','书面表达'], boundaries:['灵活变通'], examples:['建议信'], tags:['写作','模板'] },
      { id:'eng10', name:'词汇拓展', description:'词根词缀法扩展词汇', subject:'english', steps:['识别词根','判断词缀','推测词义'], triggers:['背单词','词根','词汇量'], boundaries:['特殊含义需单独记'], examples:['un/dis/in'], tags:['词汇','词根'] },
    ],
  },
  {
    id: 'study-method-tutor',
    name: '策无遗',
    title: '学习方法策略教练',
    description: '专攻学习策略与应试方法，8个模块覆盖提分分析、瓶颈突破、考试抢分',
    avatar: '🎯',
    color: '#14B8A6',
    skills: [
      { id:'met01', name:'投入产出分析', description:'分析各科提分性价比', subject:'method', steps:['统计当前水平','分析提分潜力','确定优先级','制定方案'], triggers:['怎么提分最快','时间不够'], boundaries:['不推荐的科也要保基础'], examples:['3个月时间分配'], tags:['提分','效率'] },
      { id:'met02', name:'瓶颈期处理', description:'成绩不提升的原因分析和突破', subject:'method', steps:['诊断当前状态','找瓶颈原因','调整策略','实施'], triggers:['成绩不动','瓶颈','没进步'], boundaries:['需坚持2周'], examples:['数学120上不去'], tags:['瓶颈','突破'] },
      { id:'met03', name:'考试抢分', description:'考场时间分配答题顺序检查技巧', subject:'method', steps:['速览定策略','先易后难','难题有预案','留时间检查'], triggers:['考试紧张','做不完','粗心'], boundaries:['难题不超15分钟'], examples:['各科时间分配'], tags:['考试','技巧'] },
      { id:'met04', name:'知识记忆方法', description:'高效记忆方法：艾宾浩斯思维导图', subject:'method', steps:['理解本质','构建框架','用技巧','定期复习'], triggers:['记不住','背了就忘'], boundaries:['理解是前提'], examples:['化学方程式记忆'], tags:['记忆','方法'] },
      { id:'met05', name:'刷题效率', description:'精刷vs题海、错题本方法', subject:'method', steps:['选好题','限时做','对答案','总结错因'], triggers:['刷题','题海','错题本'], boundaries:['重质量不重数量'], examples:['错题本模板'], tags:['刷题','效率'] },
      { id:'met06', name:'学科套路', description:'各科常见题型和解题套路', subject:'method', steps:['识别题型','匹配套路','灵活运用'], triggers:['套路','模板','固定题型'], boundaries:['套路不替代理解'], examples:['压轴题套路'], tags:['套路','题型'] },
      { id:'met07', name:'学习动力', description:'动力不足分析和激励方法', subject:'method', steps:['分析原因','设目标','建反馈','养习惯'], triggers:['不想学','没动力','拖延'], boundaries:['需找到内在动力'], examples:['每日小目标'], tags:['动力','心态'] },
      { id:'met08', name:'志愿填报', description:'中考志愿填报策略', subject:'method', steps:['了解分数线','评估水平','定策略','确认填报'], triggers:['志愿','填志愿','选学校'], boundaries:['保守还是冲要结合自身'], examples:['梯度填报'], tags:['志愿','填报'] },
    ],
  },
];

export const SUBJECTS = [
  { id:'math', label:'数学', icon:'📐', agentId:'math-tutor' },
  { id:'physics', label:'物理', icon:'⚡', agentId:'physics-tutor' },
  { id:'chemistry', label:'化学', icon:'🔬', agentId:'chemistry-tutor' },
  { id:'chinese', label:'语文', icon:'📖', agentId:'chinese-tutor' },
  { id:'english', label:'英语', icon:'🌍', agentId:'english-tutor' },
  { id:'method', label:'学习方法', icon:'🎯', agentId:'study-method-tutor' },
];

export const PRICING_PLANS = [
  { id:'free', name:'免费体验', price:0, period:'永久', description:'每日30次提问', features:['每日30次对话','1000积分','基础AI回答'], popular:false, dailyLimit:30, credits:1000 },
  { id:'monthly', name:'月度会员', price:39, period:'月', description:'不限对话次数', features:['不限对话次数','全科6位AI专家','技能地图'], popular:false, dailyLimit:-1, credits:0 },
  { id:'yearly', name:'年度会员', price:299, period:'年', description:'不限对话+赠送积分', features:['不限对话次数','全科6位AI专家','技能地图','赠送5000积分','学情诊断','优先更新'], popular:true, dailyLimit:-1, credits:5000 },
];

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
