-- 中考提分AI私教 - Supabase数据库初始化
-- 在Supabase Dashboard -> SQL Editor中运行

-- 1. 用户档案表
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 新用户注册时自动创建档案
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)));
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2. 订阅表
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  plan text not null check (plan in ('monthly', 'yearly')),
  status text not null default 'active' check (status in ('active', 'expired', 'cancelled')),
  started_at timestamptz default now(),
  expires_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_subscriptions_user_id on public.subscriptions(user_id);
create index if not exists idx_subscriptions_status on public.subscriptions(status);

-- 3. 对话记录（可选）
create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  agent_id text not null,
  title text,
  messages jsonb not null default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_chat_history_user_id on public.chat_history(user_id);

-- 4. 行级安全策略（RLS）
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.chat_history enable row level security;

-- 用户只能看自己的数据
create policy user_profiles_policy on public.profiles for all using (auth.uid() = id);
create policy user_subscriptions_policy on public.subscriptions for select using (auth.uid() = user_id);
create policy user_chat_policy on public.chat_history for all using (auth.uid() = user_id);
