-- ============================================
-- 中考提分AI私教 - 完整数据库初始化（一键执行）
-- 在 Supabase Dashboard → SQL Editor 中粘贴执行
-- ============================================

-- 1. 用户档案表（如果不存在）
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 新用户注册时自动创建档案
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. 积分表
CREATE TABLE IF NOT EXISTS public.credits (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
  balance INTEGER NOT NULL DEFAULT 3000,
  total_used INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_credits_user_id ON public.credits(user_id);

-- 3. 积分交易记录
CREATE TABLE IF NOT EXISTS public.credit_transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('grant', 'deduct', 'purchase', 'subscription')),
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_credit_tx_user_id ON public.credit_transactions(user_id);

-- 4. 聊天历史表
CREATE TABLE IF NOT EXISTS public.chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  agent_id TEXT NOT NULL,
  title TEXT DEFAULT '新对话',
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON public.chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_updated ON public.chat_history(updated_at DESC);

-- 5. 用户设置表
CREATE TABLE IF NOT EXISTS public.user_settings (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  custom_api_key TEXT,
  custom_provider_id TEXT,
  use_default_api BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 行级安全策略（RLS）
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- 删除旧策略（如果有）
DROP POLICY IF EXISTS user_profiles_policy ON public.profiles;
DROP POLICY IF EXISTS user_credits_policy ON public.credits;
DROP POLICY IF EXISTS user_credit_tx_policy ON public.credit_transactions;
DROP POLICY IF EXISTS user_chat_policy ON public.chat_history;
DROP POLICY IF EXISTS user_settings_policy ON public.user_settings;

-- 创建新策略：用户只能操作自己的数据
CREATE POLICY user_profiles_policy ON public.profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY user_credits_policy ON public.credits FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_credit_tx_policy ON public.credit_transactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_chat_policy ON public.chat_history FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_settings_policy ON public.user_settings FOR ALL USING (auth.uid() = user_id);

-- 7. 邮箱验证后赠送积分
CREATE OR REPLACE FUNCTION public.handle_email_confirmed()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email_confirmed_at IS NOT NULL AND (OLD.email_confirmed_at IS NULL) THEN
    INSERT INTO public.credits (user_id, balance)
    VALUES (NEW.id, 3000)
    ON CONFLICT (user_id) DO NOTHING;
    INSERT INTO public.credit_transactions (user_id, amount, type, description)
    VALUES (NEW.id, 3000, 'grant', '注册赠送');
    INSERT INTO public.user_settings (user_id, use_default_api)
    VALUES (NEW.id, TRUE)
    ON CONFLICT (user_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_email_confirmed ON auth.users;
CREATE TRIGGER on_auth_email_confirmed
  AFTER UPDATE ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_email_confirmed();

-- 8. 给已确认邮箱但没有积分的用户补发
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT u.id FROM auth.users u
    WHERE u.email_confirmed_at IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM public.credits c WHERE c.user_id = u.id)
  LOOP
    INSERT INTO public.credits (user_id, balance) VALUES (r.id, 3000) ON CONFLICT DO NOTHING;
    INSERT INTO public.credit_transactions (user_id, amount, type, description)
    VALUES (r.id, 3000, 'grant', '补发注册赠送');
  END LOOP;
END;
$$;