-- 中考提分AI私教 - 完整数据库

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  plan TEXT NOT NULL CHECK (plan IN ('monthly', 'yearly')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'cancelled')),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);

CREATE TABLE IF NOT EXISTS public.credits (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
  balance INTEGER NOT NULL DEFAULT 100,
  total_used INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_credits_user_id ON public.credits(user_id);

CREATE TABLE IF NOT EXISTS public.credit_transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('grant', 'deduct', 'purchase', 'subscription')),
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_credit_tx_user_id ON public.credit_transactions(user_id);

CREATE TABLE IF NOT EXISTS public.chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  agent_id TEXT NOT NULL,
  title TEXT DEFAULT '新对话',
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON public.chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_updated ON public.chat_history(updated_at DESC);

CREATE TABLE IF NOT EXISTS public.user_settings (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  custom_api_key TEXT,
  custom_provider_id TEXT,
  use_default_api BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_usage (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  usage_date DATE NOT NULL DEFAULT CURRENT_DATE,
  message_count INTEGER NOT NULL DEFAULT 1,
  UNIQUE(user_id, usage_date)
);
CREATE INDEX IF NOT EXISTS idx_daily_usage_user_date ON public.daily_usage(user_id, usage_date);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_usage ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_profiles_policy ON public.profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY user_subscriptions_select ON public.subscriptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY user_subscriptions_insert ON public.subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY user_subscriptions_update ON public.subscriptions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY user_credits_policy ON public.credits FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_credit_tx_policy ON public.credit_transactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_chat_policy ON public.chat_history FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_settings_policy ON public.user_settings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_daily_usage_policy ON public.daily_usage FOR ALL USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;
  INSERT INTO public.credits (user_id, balance)
  VALUES (NEW.id, 100)
  ON CONFLICT (user_id) DO NOTHING;
  INSERT INTO public.user_settings (user_id, use_default_api)
  VALUES (NEW.id, TRUE)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER update_credits_updated_at BEFORE UPDATE ON public.credits
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER update_chat_history_updated_at BEFORE UPDATE ON public.chat_history
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
CREATE TRIGGER update_user_settings_updated_at BEFORE UPDATE ON public.user_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE OR REPLACE FUNCTION public.get_credits_balance(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE v_balance INTEGER;
BEGIN
  SELECT balance INTO v_balance FROM public.credits WHERE user_id = p_user_id;
  RETURN COALESCE(v_balance, 100);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_user_plan(p_user_id UUID)
RETURNS TEXT AS $$
DECLARE v_plan TEXT;
BEGIN
  SELECT plan INTO v_plan FROM public.subscriptions
  WHERE user_id = p_user_id AND status = 'active'
    AND (expires_at IS NULL OR expires_at > NOW())
  ORDER BY expires_at DESC LIMIT 1;
  RETURN COALESCE(v_plan, 'free');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_daily_message_count(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE v_count INTEGER;
BEGIN
  SELECT message_count INTO v_count FROM public.daily_usage
  WHERE user_id = p_user_id AND usage_date = CURRENT_DATE;
  RETURN COALESCE(v_count, 0);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.increment_daily_usage(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE v_new_count INTEGER;
BEGIN
  INSERT INTO public.daily_usage (user_id, usage_date, message_count)
  VALUES (p_user_id, CURRENT_DATE, 1)
  ON CONFLICT (user_id, usage_date)
  DO UPDATE SET message_count = public.daily_usage.message_count + 1;
  SELECT message_count INTO v_new_count FROM public.daily_usage
  WHERE user_id = p_user_id AND usage_date = CURRENT_DATE;
  RETURN v_new_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.deduct_credits_atomic(
  p_user_id UUID,
  p_amount INTEGER,
  p_description TEXT
) RETURNS TABLE(success BOOLEAN, new_balance INTEGER, error TEXT) AS $$
DECLARE v_current_balance INTEGER;
BEGIN
  SELECT balance INTO v_current_balance FROM public.credits WHERE user_id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT FALSE, 0, '积分记录不存在'::TEXT;
    RETURN;
  END IF;
  IF v_current_balance < p_amount THEN
    RETURN QUERY SELECT FALSE, v_current_balance, '积分不足'::TEXT;
    RETURN;
  END IF;
  UPDATE public.credits
  SET balance = balance - p_amount, total_used = total_used + p_amount, updated_at = NOW()
  WHERE user_id = p_user_id;
  INSERT INTO public.credit_transactions (user_id, amount, type, description)
  VALUES (p_user_id, -p_amount, 'deduct', p_description);
  RETURN QUERY SELECT TRUE, v_current_balance - p_amount, NULL::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.grant_credits(p_user_id UUID, p_amount INTEGER, p_description TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.credits SET balance = balance + p_amount, updated_at = NOW() WHERE user_id = p_user_id;
  INSERT INTO public.credit_transactions (user_id, amount, type, description)
  VALUES (p_user_id, p_amount, 'grant', p_description);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.deduct_credits_atomic TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_plan TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_daily_message_count TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_daily_usage TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_credits_balance TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_credits TO authenticated;
