-- 中考提分AI私教 - 完整数据库（一键执行）

-- ============================================
-- 1. 表结构
-- ============================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  plan TEXT NOT NULL CHECK (plan IN ('monthly', 'yearly')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'cancelled')),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);

CREATE TABLE IF NOT EXISTS public.credits (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
  balance INTEGER NOT NULL DEFAULT 100,
  total_used INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_credits_user_id ON public.credits(user_id);

CREATE TABLE IF NOT EXISTS public.credit_transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('grant', 'deduct', 'purchase', 'subscription')),
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_credit_tx_user_id ON public.credit_transactions(user_id);

CREATE TABLE IF NOT EXISTS public.chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  agent_id TEXT NOT NULL,
  title TEXT DEFAULT '新对话',
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON public.chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_updated ON public.chat_history(updated_at DESC);

CREATE TABLE IF NOT EXISTS public.user_settings (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  custom_api_key TEXT,
  custom_provider_id TEXT,
  use_default_api BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_usage (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  usage_date DATE NOT NULL DEFAULT CURRENT_DATE,
  message_count INTEGER NOT NULL DEFAULT 1,
  UNIQUE(user_id, usage_date)
);
CREATE INDEX IF NOT EXISTS idx_daily_usage_user_date ON public.daily_usage(user_id, usage_date);

-- ============================================
-- 2. RLS 策略
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_usage ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_profiles_policy ON public.profiles;
DROP POLICY IF EXISTS user_subscriptions_select ON public.subscriptions;
DROP POLICY IF EXISTS user_subscriptions_insert ON public.subscriptions;
DROP POLICY IF EXISTS user_subscriptions_update ON public.subscriptions;
DROP POLICY IF EXISTS user_credits_policy ON public.credits;
DROP POLICY IF EXISTS user_credit_tx_policy ON public.credit_transactions;
DROP POLICY IF EXISTS user_chat_policy ON public.chat_history;
DROP POLICY IF EXISTS user_settings_policy ON public.user_settings;
DROP POLICY IF EXISTS user_daily_usage_policy ON public.daily_usage;

CREATE POLICY user_profiles_policy ON public.profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY user_subscriptions_select ON public.subscriptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY user_subscriptions_insert ON public.subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY user_subscriptions_update ON public.subscriptions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY user_credits_policy ON public.credits FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_credit_tx_policy ON public.credit_transactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_chat_policy ON public.chat_history FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_settings_policy ON public.user_settings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_daily_usage_policy ON public.daily_usage FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 3. 触发器函数
-- ============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;
  INSERT INTO public.credits (user_id, balance)
  VALUES (NEW.id, 100)
  ON CONFLICT (user_id) DO NOTHING;
  INSERT INTO public.user_settings (user_id, use_default_api)
  VALUES (NEW.id, TRUE)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS update_credits_updated_at ON public.credits;
CREATE TRIGGER update_credits_updated_at BEFORE UPDATE ON public.credits
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS update_chat_history_updated_at ON public.chat_history;
CREATE TRIGGER update_chat_history_updated_at BEFORE UPDATE ON public.chat_history
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS update_user_settings_updated_at ON public.user_settings;
CREATE TRIGGER update_user_settings_updated_at BEFORE UPDATE ON public.user_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================
-- 4. RPC 函数（绕过 RLS）
-- ============================================

CREATE OR REPLACE FUNCTION public.get_credits_balance(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE v_balance INTEGER;
BEGIN
  SELECT balance INTO v_balance FROM public.credits WHERE user_id = p_user_id;
  RETURN COALESCE(v_balance, 100);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_user_plan(p_user_id UUID)
RETURNS TEXT AS $$
DECLARE v_plan TEXT;
BEGIN
  SELECT plan INTO v_plan FROM public.subscriptions
  WHERE user_id = p_user_id AND status = 'active'
    AND (expires_at IS NULL OR expires_at > NOW())
  ORDER BY expires_at DESC LIMIT 1;
  RETURN COALESCE(v_plan, 'free');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_daily_message_count(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE v_count INTEGER;
BEGIN
  SELECT message_count INTO v_count FROM public.daily_usage
  WHERE user_id = p_user_id AND usage_date = CURRENT_DATE;
  RETURN COALESCE(v_count, 0);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.increment_daily_usage(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE v_new_count INTEGER;
BEGIN
  INSERT INTO public.daily_usage (user_id, usage_date, message_count)
  VALUES (p_user_id, CURRENT_DATE, 1)
  ON CONFLICT (user_id, usage_date)
  DO UPDATE SET message_count = public.daily_usage.message_count + 1;
  SELECT message_count INTO v_new_count FROM public.daily_usage
  WHERE user_id = p_user_id AND usage_date = CURRENT_DATE;
  RETURN v_new_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.deduct_credits_atomic(
  p_user_id UUID,
  p_amount INTEGER,
  p_description TEXT
) RETURNS TABLE(success BOOLEAN, new_balance INTEGER, error TEXT) AS $$
DECLARE v_current_balance INTEGER;
BEGIN
  SELECT balance INTO v_current_balance FROM public.credits WHERE user_id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT FALSE, 0, '积分记录不存在'::TEXT;
    RETURN;
  END IF;
  IF v_current_balance < p_amount THEN
    RETURN QUERY SELECT FALSE, v_current_balance, '积分不足'::TEXT;
    RETURN;
  END IF;
  UPDATE public.credits
  SET balance = balance - p_amount, total_used = total_used + p_amount, updated_at = NOW()
  WHERE user_id = p_user_id;
  INSERT INTO public.credit_transactions (user_id, amount, type, description)
  VALUES (p_user_id, -p_amount, 'deduct', p_description);
  RETURN QUERY SELECT TRUE, v_current_balance - p_amount, NULL::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.grant_credits(p_user_id UUID, p_amount INTEGER, p_description TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.credits SET balance = balance + p_amount, updated_at = NOW() WHERE user_id = p_user_id;
  INSERT INTO public.credit_transactions (user_id, amount, type, description)
  VALUES (p_user_id, p_amount, 'grant', p_description);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 5. 聊天历史 RPC 函数（之前缺失的关键函数）
-- ============================================

CREATE OR REPLACE FUNCTION public.get_chat_history(p_user_id UUID)
RETURNS TABLE(id BIGINT, agent_id TEXT, title TEXT, messages JSONB, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ) AS $$
BEGIN
  RETURN QUERY
  SELECT ch.id, ch.agent_id, ch.title, ch.messages, ch.created_at, ch.updated_at
  FROM public.chat_history ch
  WHERE ch.user_id = p_user_id
  ORDER BY ch.updated_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.save_chat_history(
  p_user_id UUID,
  p_agent_id TEXT,
  p_title TEXT,
  p_messages JSONB
) RETURNS BIGINT AS $$
DECLARE v_id BIGINT;
BEGIN
  INSERT INTO public.chat_history (user_id, agent_id, title, messages)
  VALUES (p_user_id, p_agent_id, p_title, p_messages)
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.update_chat_history(
  p_id BIGINT,
  p_user_id UUID,
  p_title TEXT,
  p_messages JSONB
) RETURNS VOID AS $$
BEGIN
  UPDATE public.chat_history
  SET title = p_title, messages = p_messages, updated_at = NOW()
  WHERE id = p_id AND user_id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 6. GRANT 权限
-- ============================================

GRANT EXECUTE ON FUNCTION public.get_credits_balance TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_plan TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_daily_message_count TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_daily_usage TO authenticated;
GRANT EXECUTE ON FUNCTION public.deduct_credits_atomic TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_credits TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_chat_history TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_chat_history TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_chat_history TO authenticated;

-- ============================================
-- 7. 修复已有用户数据（积分重置为100）
-- ============================================

-- 为所有已有用户补建 profiles（如果缺失）
INSERT INTO public.profiles (id, email)
SELECT id, email FROM auth.users
WHERE id NOT IN (SELECT id FROM public.profiles)
ON CONFLICT (id) DO NOTHING;

-- 为所有已有用户补建积分记录（如果缺失）
INSERT INTO public.credits (user_id, balance)
SELECT id, 100 FROM auth.users
WHERE id NOT IN (SELECT user_id FROM public.credits)
ON CONFLICT (user_id) DO NOTHING;

-- 重置所有积分为100
UPDATE public.credits SET balance = 100, total_used = 0, updated_at = NOW();

-- 重置今日限制
DELETE FROM public.daily_usage WHERE usage_date = CURRENT_DATE;

SELECT '数据库初始化完成！' as result;